name: Multi-Country Finance Job Scraper

on:
  schedule:
    # Run daily at 7:00 AM UAE time (3:00 AM UTC)
    # UAE is UTC+4, so 7 AM UAE = 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allow manual triggers for testing

jobs:
  scrape-finance-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas openpyxl lxml html5lib
        
- name: Run job scraper
  env:
    EMAIL_USER: ${{ secrets.EMAIL_USER }}
    EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
  run: |
    echo "Starting job scraper at $(date)"
    echo "Python version: $(python --version)"
    echo "Pip version: $(pip --version)"
    echo "Installed packages:"
    pip list
    echo "Files in current directory:"
    ls -la
    echo "Checking if Excel file exists:"
    ls -la "top companies.xlsx" || echo "Excel file not found!"
    echo "Running Python script with verbose output:"
    python -u scraper.py 2>&1 || echo "Python script failed with exit code $?"
    echo "Job scraper completed at $(date)"
        
    - name: Commit updated seen jobs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen_jobs.json
        git diff --staged --quiet || git commit -m "Update seen jobs database - $(date '+%Y-%m-%d %H:%M UTC')"
        git push
      continue-on-error: true
        
    - name: Upload logs (if scraper fails)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-logs
        path: |
          *.log
          seen_jobs.json
        retention-days: 7
