name: Multi-Country Finance Job Scraper

on:
  schedule:
    # Run daily at 7:00 AM UAE time (3:00 AM UTC)
    - cron: '0 3 * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-finance-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0 beautifulsoup4==4.12.2 pandas==2.1.4 openpyxl==3.1.2 lxml==4.9.3
        
    - name: Debug environment
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Current directory contents:"
        ls -la
        echo "Checking for Excel file:"
        if [ -f "top companies.xlsx" ]; then
          echo "✅ Excel file found: top companies.xlsx"
          file "top companies.xlsx"
        else
          echo "❌ Excel file 'top companies.xlsx' not found"
          echo "Available files:"
          find . -name "*.xlsx" -o -name "*.xls"
        fi
        echo "Environment variables set:"
        echo "EMAIL_USER: ${EMAIL_USER:+SET}"
        echo "EMAIL_PASS: ${EMAIL_PASS:+SET}"
        echo "RECIPIENT_EMAIL: ${RECIPIENT_EMAIL:+SET}"
        
    - name: Run job scraper
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "🔍 Starting job scraper at $(date)"
        python -u scraper.py
        echo "✅ Job scraper completed at $(date)"
        
    - name: Commit updated seen jobs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen_jobs.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update seen jobs database - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        fi
      continue-on-error: true
        
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: |
          seen_jobs.json
        retention-days: 3
